### PR TITLE
#35 only set defaults on create

### PR DESCRIPTION
**Pull request by lcdservices**

### CODE REVIEW

**Comment by agileware-justin** [comment]
Good to merge.

**Comment by lcdservices** [comment]
@eileenmcnaughton wondering if we can get this merged for the next release.

**Comment by agileware-justin** [comment]
@eileenmcnaughton can you please tag a new release which includes this fix 1.9.2?

**Comment by eileenmcnaughton** [comment]
@agileware-justin yeah - I thought about that - I want to re-run civix again first I think to get it updated to the latest civix code

**Comment by agileware-justin** [comment]
civix latest updates have been very problematic YMMV and worth a close inspection.

**Comment by eileenmcnaughton** [comment]
hmm ok - I haven't hit any problems with them but you should log whatever you hit in gitlab

**Pull request merged**
