### PR TITLE
Support overriding is_permission_a_b/b_a on Relationship.Get API

### PR DESCRIPTION
**Pull request by mattwire**
This adds support for overriding Relationship permissions via the API.

I've also updated the TODO/README, please check if the changes are correct?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
So I went to look at this & was surprised to discover all these features I didn't know existed :-) I guess I've been merging kinda on trust for a while now :-) Anyway I tested this & obviously there is still a todo on it around the js error - on the bright side I think @aydun will be at the sprint & he wrote the js so this just needs a wee huddle

**Comment by aydun** [comment]
Hi @mattwire - not sure about this ... the setting is used in the GUI to override the specified permission when relationships are created/updated, so I think an apiwrapper around Relationship.create would be more appropriate.  Doing it on Relationship.get will lead to different results for is_permission depending on whether the lookup is via api or other methods.

**Comment by mattwire** [comment]
@aydun I think part the problem is this extension has been gradually added to.  My interpretation of the "Enforce permissions" is that it should be enforced for all relationships of that type - including existing ones.

Can you see a use-case where you would not want to enforce for pre-existing relationships? I can see that getting messy pretty quickly..

In it's current state, it is really only a UI "freeze" and doesn't actually enforce anything! I take your point about having a wrapper around Relationship.create as well but it is not easy to override the BAO_Get method to enforce the permissions - the "fix" there is to encourage use of the API I think.

**Comment by aydun** [comment]
@mattwire I think that one is likely to want to enforce permissions on existing relationships, but we need to find an appropriate workflow: changing the setting to 'enforce' from 'default' or changing the enforced value should not change potentially thousands of relationships without appropriate confirmation.  At the moment, it is effectively "Enforce permissions on new and edited relationships when done via the GUI".  It's not really about a use case for not enforcing on pre-existing but about being cautious with bulk data changes.

This extension itself reads the permission values direct from the civicrm_relationship table so a wrapper on Relationship.get will tell us the relationship is permissioned while not actually working that way in this extension.

Maybe an api call to update existing relationships with enforced permissions is the way to go?

**Comment by mattwire** [comment]
> Maybe an api call to update existing relationships with enforced permissions is the way to go?

Right, that sounds sensible.  So a wrapper on Relationship.create instead of Relationship.get and an API call to bulk update existing permissions (if we can't already do that).  Watch this space...

**Comment by aydun** [comment]
Actually, I don't think the API wrapper on Relationship.create is needed:  the permissions are enforced by the pre hook.  The jquery stuff is to try to avoid confusing the user!  Previously, the permissions were enforced by the pre hook whatever the user selected in the GUI which was confusing.

So an api job just calling a no-op create on Relationship might be enough.

**Pull request closed without merging**
