### PR TITLE
Replace entitySettings with custom-data-on-any

### PR DESCRIPTION
**Pull request by aydun**
Here's an 'early cut' of a PR to use custom-data-on-any instead of entitySettings.

There are a few things to be done (see TODO.md) but I am opening this now in the hope that someone might review or continue work on this while I'm off on holiday since it would be great to have a new extension release out to tie in with the release of dev/core#34 in 5.5.0

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@petednz do you want to get @jitendrapurohit or Luke to check this out? Maybe @MegaphoneJon  also has an interest

Note in core it will be possible as of 5.5 to distinguish between read & edit
+ edit perms on a relationship.

Also note that if this doesn't work on all versions we will increment the version in info.xml rather than try to contort the code. (that's my general extension approach post the version renumbering)

**Comment by petednz** [comment]
read and read?

**Comment by eileenmcnaughton** [comment]
@petednz you mis-read - see above :-)

**Comment by petednz** [comment]
I believe you - i just don't know how to read it differently ;-)

"Note in core it will be possible as of 5.5 to distinguish between read & read"

**Comment by eileenmcnaughton** [comment]
@petednz your eyes deceive you - it never said that :-)

**Comment by petednz** [comment]
ok - well i am glad i didn't copy and paste to give me any evidence then, Officer

**Comment by aydun** [comment]
Hi all, just wondering whether anyone has made progress testing this?

**Comment by eileenmcnaughton** [comment]
@aydun doesn't look like it - I'm gonna merge it - I don't hold my extensions to the review standard I hold for core - I'm happy to let any issues come out in the wash here

**Pull request merged**
